<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>McTextureGhost</RootNamespace>
    <AssemblyName>McTextureGhost</AssemblyName>
    <!-- Needed for System.Drawing based placeholder PNG generation -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>

    <!-- App Identity & Metadata -->
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Product>McTextureGhost</Product>
    <AssemblyTitle>McTextureGhost</AssemblyTitle>
    <Authors>navoyovan</Authors>
    <Version>0.1.0</Version>
    <Description>Missing texture manager and asset scaffolding utility for Minecraft Bedrock resource packs.</Description>
    <Copyright>© 2026 navoyovan</Copyright>

    <!-- Ensure nuget.org is used during restore so SDK/ref packages are found -->
    <RestoreSources>$(RestoreSources);https://api.nuget.org/v3/index.json</RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
    <PackageReference Include="VirtualizingWrapPanel" Version="2.5.4" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <Resource Include="icon.ico" />
    <Resource Include="Resources\Fonts\*.ttf" />
  </ItemGroup>

</Project>